config/config.go
The names were changed to registry-username and registry-password, but this
required change (where we actually pull in values) was left behind
=> Update CLI command registry flags

pkg/cli/cli.go
The bootstrap edge route to Control API used by the operator for configuring mesh objects needs to exclude the `/v1.0` prefix.
=> Fix Control API bootstrap route

scripts/bootstrap
`kustomize` CLI is no longer needed for working in this project since we import its Go API directly. It's also available via `kubectl apply -k`.
=> Remove kustomize from bootstrap script

README.md, pkg/cuemodule/meshconfigs/defaults.cue
Reverts an addition to mesh config default values. `require_tls` should not be set on _all_ clusters by default. Instead, `require_tls` is set on clusters that are upstreams of:
- [edge](https://github.com/greymatter-io/operator/blob/8ef1e52fe3484ce3442e684e300e8c3507ed98c0/pkg/cuemodule/meshconfigs/spire.cue#L18)
- [other workloads](https://github.com/greymatter-io/operator/blob/8ef1e52fe3484ce3442e684e300e8c3507ed98c0/pkg/cuemodule/meshconfigs/spire.cue#L46)
=> Do not set require_tls on clusters by default

CHANGELOG.md, pkg/installer/spire.yaml, scripts/build
Updated the versions of Spire images (spire-server, spire-agent, and the k8s-workload-registrar) that the operator installs to 1.2.0. This fixes an issue on some platforms where Spire would misidentify the process as non-k8s, and fail to issue an identity, causing a chain of failures when the static config of the control-api, catalog, and gm-redis sidecars fail to make connections.
=> Bump spire version to fix Spire attestation

CHANGELOG.md, pkg/installer/installer.go
We are going to yank tag v0.3.1, since it never made it to the wild.
=> Release operator 0.3.2

CHANGELOG.md, pkg/installer/spire.yaml
`--registrationUDSPath` is a deprecated way of specifying the UDS path, and we recently updated the Spire components. The new flag is `-socketPath`. This fixes a bug where the liveness probe on spire server would eventually fail, causing Kubernetes to kill the container.
=> swapping out deprecated flag in spire server health check

CHANGELOG.md
Release 0.3.2 will be yanked due to the most recent commits related to spire
configuration.
=> Release operator 0.3.3

scripts/build
Example usage:
./scripts/build debug
This bloats the binary a little but embeds all debug symbols.
=> Add a debug build mode

pkg/installer/spire.yaml
Since our spire config is all-k8s, we shouldn't need this workload
attestor. This might save us some spam in the logs.
=> Remove unix WorkloadAttestor from spire config

.buildkite/e2e_vm.yaml
Adding (temporarily?) a separate buildkite file, constrained to a
baremetal host. Right now this is one of my lesser-used computers.
We need a baremetal host, because we want to create a build that
launches a full-blown Ubuntu virtual machine. This is possible with the
standard LXD images by just passing `--vm` plus some optional config
parameters.
We need a VM instead of a linux container, because we want to launch an
ephemeral, single-node Kubernetes environment inside.
Again, the actual buildkite agent runs on bare metal, and must be given
access to lxd. Once that's done, standup/teardown can be orchestrated
from outside the VM, with the lxc cli.
=> Add e2e VM build

CHANGELOG.md, pkg/cuemodule/base/wellknown.cue, pkg/installer/install.go, pkg/webhooks/workloads.go, pkg/wellknown/wellknown.go
This was necessary to make clear instructions for GitOps-based deployments in our docs, and trivial enough to do in passing.
We've added this annotation to the operator for Deployments and StatefulSets:
```
metadata:
annotation:
greymatter.io/configure-sidecar: "false"
```
If set to "false", the operator will inject a sidecar but leave it unconfigured so users can manually configure it.
Also in this PR
- Changelog update
- Some refactoring of magic strings into constants
=> Add annotation for disabling sidecar configuration

README.md, scripts/cibuild
[sc-10466]
"Hello Dilbert, I'm the vice-president in charge of immediately implementing ideas..."  
--Dilbert Episode 2
Here's a PR. Do not trust this PR - Make sure this is what you actually want. In particular, please confirm that the CI build container has a new enough version of kubectl that it can still build the operator after this PR.
I'm just throwing something up there because when I went through all of the Operator PRs, two of them stood out as handy and completely trivial, so I resolved to just do them right now. I just naively applied what Brian said here:
https://app.shortcut.com/grey-matter/story/10466/operator-replace-kustomize-cli-with-kubectl
=> replace `kustomize build` with `kubectl kustomize`

.buildkite/pipeline.yaml
2104 was built from a non-LTS release, so we upgrade it with the next non-LTS release.
Hopefully we can get rid of non-LTS releases entirely with the next LTS (22.04)
=> Use ubuntu-2110-ci buildkite container

.gitmodules
We needed to create a branch pre_refactor in the greymatter-cue repo, and we use
that as our submodule. HEAD should be this commit
36dd308eefd7585fafa6139ce2c29755e674fd58
Once our CUE refactor is done, we can tag releases in greymatter-cue
which submodules can also use.
=> Submodules cannot pin to a commit, only track HEAD

scripts/bootstrap
This isn't required to do most of the dev work that's happening these
days, so there's no reason to fail the build for it.
=> Remove requirement for operator-sdk in bootstrap

pkg/cuemodule/inputs.cue, pkg/cuemodule/k8s/outputs/controlensemble.cue
[sc-13230]
Also noticed a vestigial volumeClaimTemplate for redis in the controlensemble manifest that can go because the redis manifest has it.
=> bump image versions from rc to release

Dockerfile, pkg/cuemodule/inputs.cue, pkg/cuemodule/k8s/outputs/operator.cue, pkg/mesh_install/installer.go
As per this conversation: https://greymatter.slack.com/archives/C07TJSLQ0/p1651009645580309?thread_ts=1650988828.618659&cid=C07TJSLQ0
I've made a new ConfigMap that gets mounted into the operator at `/app/overrides.cue`, allowing a user to override values. At the moment, the point is to let the integration tests flip switches _somehow_, and may not end up being the ultimate solution.
~Personally, I'm not very happy with this, but it'll do for now.~ I've found a version of this I'm happy enough with. See below.
=> ConfigMap that can be used to override config

.buildkite/pipeline.yaml, scripts/cibuild, scripts/test
Please see https://buildkite.com/greymatter/operator/builds/554 for the status of the tests.
This pr adds a few features. 
First, the wait times for async actions, like
installing the operator, are minimized by replacing estimated sleeps with
polling. Particularly, the wait_for_resource and curl_retry use polling with a
few second delay to effectively wait for pods and other resources to become
available and for servers to begin accepting requests, respectively.
Second, the pr adds stricter and more test assertions. These include actions like
testing for existence (and lack thereof) of pods, testing network
accessibility, and testing for readiness by a timeout (failing to be ready by a
timeout likely indicates an error as the timeouts are generous). 
Lastly, the pr expands the testing …
=> Optimize and expand integration tests

.buildkite/pipeline.yaml, scripts/cibuild
The CI process shouldn't release binaries or containers if the integration tests (or any tests) fail. This pr fixes that issue by breaking out the release command into its own step, where with the buildkite wait command, will run only if the previous step succeeds.
=> Pipeline releases only after integration tests succeed.

CHANGELOG.md, pkg/cuemodule/gm/outputs/catalogentries.cue, pkg/cuemodule/k8s/outputs/dashboard.cue
Fixes [sc-13236], [sc-13302], [sc-10560] by setting the correct control-api URL in the Dashboard's CONFIG_SERVER environment variable and Control API's Catalog entry.
To test: Do the Getting Started into a fresh reset of Rancher Desktop, then open one of the card's side panels and confirm you can change business impacts, and click the 'Grey Matter-DP' button.
=> Fixing business impact and config inspection by pointing dashboard to the right place

README.md, pkg/webhooks/workloads.go, scripts/build
[sc-13384]
Turns out I just wasn’t even checking that the pod was in the watched namespaces before injecting a sidecar, so… easy fix.
Also includes a minor fix to the debug build script and instructions.
If you want to test this, follow the Getting Started instructions in the README, then deploy a workload into a _watched_ namespace (the default mesh watches only the `default` namespace) and another into an _unwatched_ namespace. A sidecar should be injected into the former (and configured) but not the latter.
=> Bugfix: Don't inject sidecar in unwatched namespaces

.buildkite/pipeline.yaml, .gitignore, pkg/cuemodule/inputs.cue, scripts/build, scripts/cibuild
[sc-13238]
Per [the plan described here](https://app.shortcut.com/grey-matter/story/13238/publish-operator-installation-manifests-to-our-website-curl-bash-script#activity-14086), build manifests to install the operator with certain flags already set.
These are intended to be published somewhere so that operator installation becomes simply a matter of applying them, e.g. with `kubectl apply -f https://greymatter.io/operator/v1.0_withspire.yaml` (followed immediately by creation of `gm-docker-secret` in the `gm-operator` namespace).
=> Build operator installation manifests

scripts/cibuild, scripts/test
This makes it so that if the path-activated systemd
service at /opt/k3s-import fails, our integration tests will
fail in a more obvious way. Relying on "latest", as usual, is bad.
=> Tag test operator image with Buildkite env vars

CHANGELOG.md
[sc-16955]
Updated Changelog following this process: https://wiki.greymatter.io/en/development-process#creating-new-releases
Once this is merged, I'll tag the tip of main `v0.9.0` and push the tag, then confirm that CI accomplishes the release of a new image.
=> Release operator 0.9.0

CHANGELOG.md, README.md, pkg/gmapi/cli.go, pkg/mesh_install/install.go, pkg/webhooks/workloads.go, scripts/cibuild
[sc-17445]
A regression is causing sidecars to be injected even if there's no inject-sidecar-to annotation on the Deployment or StatefulSet. This PR should fix that.
[sc-17490]
Besides documentation on that, this PR also updates the CI build to use Quay.io for Grey Matter component images, bumps `pkg/cuemodule/core` to the latest gitops-core, and creates watched namespaces automatically when they don't already exist.
=> Don't inject sidecar if inject-sidecar-to annotation not present

CHANGELOG.md, Dockerfile, Dockerfile.debug, pkg/gmapi/cli.go, pkg/gmapi/client.go, pkg/gmapi/commands.go, scripts/get_greymatter_cli
[sc-19021]
This turned out to be quite straightforward, despite some unrelated weirdness holding things up. Two changes needed to be made in the operator to support the 4.0.1 -> 4.2.0 upgrade, other than the upgrade itself:
- "host" -> "url" in the embedded config.toml
- use error codes instead of a response containing "200"
If the build succeeds, this PR is good to go, since the integration tests exercise the mesh config deployment code including using the new CLI version.
=> Upgrade packaged CLI to 4.2

.buildkite/pipeline.yaml, .buildkite/scheduled-build.yaml
22.04 is preferred; it is a long-term release (LTS). Refs [sc-12654]
=> Change CI container to ubuntu-2204-ci
